version: "3"
services:
  postgres:
    # image: "postgres:latest"
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: postgres_password
  redis:
    image: "redis:latest"
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "3050:80"
  api:
    build:
      # dockerfile: Dockerfile.dev
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - NODE_ENV=development
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
      - PGDATABASE=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  client:
    build:
      dockerfile: Dockerfile.dev
      # dockerfile: "aryan390/multi-client"
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - WDS_SOCKET_PORT=0
  worker:
    build:
      dockerfile: Dockerfile.dev
      # dockerfile: "aryan390/multi-worker"
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
